endpoint: "wss://kusama-rpc.polkadot.io/"
port: 3000
logLevel: info
environment: production
validatorFromGit: #optional
  enabled: false
  platform: gitLab
  private: 
    enabled: true
    apiToken: xxx
  network: kusama
  url: http://your.gitlab.domain/api/v4/projects/number/repository/files/accounts.yaml/raw?ref=main"
validators: #optional
- name: test
  address: Gt6HqWBhdu4Sy1u8ASTbS1qf2Ac5gwdegwr8tWN8saMxPt5
  expected: #optional
    commission: 0.17 #optional
    payee: Gt6HqWBhdu4Sy1u8ASTbS1qf2Ac5gwdegwr8tWN8saMxPt5 #optional